#!/usr/bin/env node
'use strict';
/**
 * archive-docs.js — preserve a local copy of every reference in the repo.
 *
 * For each entry in data/forum.json references[], download a snapshot of the
 * document into data/archive/<type>/<id>.<ext> (organized by reference type;
 * html or pdf). The source is the reference's Internet Archive Wayback capture
 * when one exists (from data/archives.json) — fetched in raw "id_" form so no
 * Wayback chrome is saved — otherwise the live URL as a last resort. A
 * generated README.md maps every saved file back to the reference it came
 * from. This turns the by-link fallback into an organized, self-documenting
 * in-repo document vault that survives link rot.
 *
 * Zero-dependency (global fetch + fs). Needs archive.org / the open internet,
 * so it runs on the Wayback collection Action, not the egress-restricted dev
 * sandbox. Incremental: existing non-trivial files are skipped unless --force.
 *
 * Usage:  node scripts/archive-docs.js [--force]
 * Writes: data/archive/<type>/<id>.<ext>, data/archive/index.json,
 *         data/archive/README.md
 * Exit 0 always (best-effort); prints a summary.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DATA_FILE = path.join(ROOT, 'data', 'forum.json');
const ARCH_FILE = path.join(ROOT, 'data', 'archives.json');
const OUT_DIR = path.join(ROOT, 'data', 'archive');

const FORCE = process.argv.includes('--force');
const TIMEOUT_MS = 60000;
const PACING_MS = 1500;
const MIN_HTML = 2048;         // bytes; below this an html save is suspect
const MIN_PDF = 10 * 1024;     // bytes

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/** Top-level folder category for a reference: its type's first word (so
 *  "commentary (critical)" and "primary/affiliated" collapse to clean, single
 *  categories like "commentary" and "primary"). */
const categoryOf = (type) => (String(type || '').match(/[a-z]+/i) || ['other'])[0].toLowerCase();
const extFor = (url) => (/\.pdf(?:$|[?#])/i.test(url) ? 'pdf' : 'html');

/** Wayback raw-resource form: insert `id_` after the timestamp. */
const rawWayback = (u) => u.replace(/(\/web\/\d{14})\//, '$1id_/');

function fmtTs(ts) {
  if (!/^\d{8}/.test(ts || '')) return '';
  return `${ts.slice(0, 4)}-${ts.slice(4, 6)}-${ts.slice(6, 8)}`;
}

async function fetchBuf(url) {
  const backoffs = [0, 6000, 15000];
  let lastErr;
  for (const wait of backoffs) {
    if (wait) await sleep(wait);
    const ctrl = new AbortController();
    const t = setTimeout(() => ctrl.abort(), TIMEOUT_MS);
    try {
      const res = await fetch(url, {
        signal: ctrl.signal,
        redirect: 'follow',
        headers: { 'User-Agent': 'fsp-archive-docs/1.0 (+https://github.com/cronologia/fsp)' },
      });
      if (!res.ok) {
        const e = new Error(`HTTP ${res.status}`);
        e.permanent = res.status === 404 || res.status === 410;
        throw e;
      }
      return Buffer.from(await res.arrayBuffer());
    } catch (err) {
      lastErr = err;
      if (err.permanent) break;
    } finally {
      clearTimeout(t);
    }
  }
  throw lastErr;
}

function writeReadme(refs, snapshots, index) {
  const rows = refs.map((r) => {
    const e = index[r.id] || {};
    const doc = e.state === 'ok' ? `\`${e.path}\`` : '— _(not saved)_';
    const snap = snapshots[r.url] && snapshots[r.url].archiveUrl;
    const archived = snap ? `[${fmtTs(snapshots[r.url].timestamp) || 'snapshot'}](${snap})` : '—';
    const orig = `[link](${r.url})`;
    return `| ${doc} | ${r.title.replace(/\|/g, '\\|')} | ${r.publisher || ''} | ${r.type || ''} | ${orig} | ${archived} |`;
  });
  const body = `# Reference document archive

Local, preserved copies of every source cited on the site — see \`data/forum.json\`
\`references[]\`. Files are grouped by reference type and named by reference id.
Each was captured from the Internet Archive's Wayback Machine (raw \`id_\` form)
where a snapshot exists, otherwise from the live URL. **Generated by
\`scripts/archive-docs.js\` — do not hand-edit.**

Last run: ${new Date().toISOString()}

| Document | Reference | Publisher | Type | Original | Archived (Wayback) |
|----------|-----------|-----------|------|----------|--------------------|
${rows.join('\n')}
`;
  fs.writeFileSync(path.join(OUT_DIR, 'README.md'), body);
}

async function main() {
  const refs = JSON.parse(fs.readFileSync(DATA_FILE, 'utf8')).references || [];
  let snapshots = {};
  try {
    snapshots = JSON.parse(fs.readFileSync(ARCH_FILE, 'utf8')).snapshots || {};
  } catch {
    console.log('note: archives.json unavailable; will fetch live URLs.');
  }
  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

  console.log(`${refs.length} references to preserve → data/archive/.`);
  const index = {};
  let ok = 0;
  let saved = 0;
  let failed = 0;
  let first = true;

  for (const r of refs) {
    const ext = extFor(r.url);
    const min = ext === 'pdf' ? MIN_PDF : MIN_HTML;
    const rel = path.join(categoryOf(r.type), `${r.id}.${ext}`);
    const out = path.join(OUT_DIR, rel);
    fs.mkdirSync(path.dirname(out), { recursive: true });

    if (!FORCE && fs.existsSync(out) && fs.statSync(out).size >= min) {
      index[r.id] = { path: rel, bytes: fs.statSync(out).size, state: 'ok' };
      ok++;
      continue;
    }

    const snap = snapshots[r.url] && snapshots[r.url].archiveUrl;
    const source = snap ? rawWayback(snap) : r.url;
    if (!first) await sleep(PACING_MS);
    first = false;

    try {
      const buf = await fetchBuf(source);
      if (ext === 'pdf' && buf.slice(0, 5).toString() !== '%PDF-') throw new Error('not a PDF payload');
      if (buf.length < min) throw new Error(`too small (${buf.length}b)`);
      fs.writeFileSync(out, buf);
      index[r.id] = { path: rel, bytes: buf.length, source: snap ? 'wayback' : 'live', state: 'ok' };
      console.log(`  ✓ ${rel} — ${(buf.length / 1024).toFixed(0)} KB (${snap ? 'wayback' : 'live'})`);
      saved++;
    } catch (err) {
      index[r.id] = { path: rel, state: 'failed', error: err.message };
      console.log(`  ✗ ${r.id} — ${err.message}`);
      failed++;
    }
  }

  fs.writeFileSync(
    path.join(OUT_DIR, 'index.json'),
    JSON.stringify(
      {
        _meta: {
          generatedBy: 'scripts/archive-docs.js',
          lastRun: new Date().toISOString(),
          note: 'Local preserved copies of every reference, grouped by type. build.js links these as "saved copy" and publishes them under docs/archive/. See README.md for provenance. Do not hand-edit.',
        },
        docs: index,
      },
      null,
      2
    ) + '\n'
  );
  writeReadme(refs, snapshots, index);
  console.log(`Done. ${ok} already saved, ${saved} newly saved, ${failed} failed → data/archive/.`);
}

if (require.main === module) {
  main().catch((err) => {
    console.error('archive-docs failed:', err);
    process.exit(0);
  });
}

module.exports = { categoryOf, extFor, writeReadme, OUT_DIR };
