#!/usr/bin/env node
'use strict';
/**
 * gen-catalog.js — generate CATALOG.md, a single human-readable reference of the
 * whole dataset: every country + FSP president, member party, membership roster,
 * armed movement, regional body, related organization, and reference.
 *
 * Zero-dependency (ADR-0001). Reads the JSON single source of truth (ADR-0002)
 * and writes CATALOG.md at the repo root. Regenerated by build.js on every build,
 * so it never drifts from the data. Do not hand-edit CATALOG.md.
 *
 * Usage: node scripts/gen-catalog.js   (or automatically via node build.js)
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const readJson = (rel) => JSON.parse(fs.readFileSync(path.join(ROOT, rel), 'utf8'));

// Escape a value for use inside a Markdown table cell.
const cell = (v) => String(v == null ? '' : v).replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
const yr = (s) => (s === 'present' ? 'present' : s);

function generate() {
  const d = readJson('data/forum.json');
  const index = readJson('data/countries/index.json');
  const countries = index.countries.map((c) => ({ meta: c, data: readJson(`data/countries/${c.code}.json`) }));

  const out = [];
  const h = (s) => out.push('', s, '');
  const p = (s) => out.push(s);

  const totalFspTerms = countries.reduce(
    (n, c) => n + c.data.presidentialSuccession.filter((x) => x.fsp).length,
    0
  );

  // ---- Header --------------------------------------------------------------
  p('# Reference catalog — Foro de São Paulo dataset');
  p('');
  p('> **Generated file — do not edit by hand.** Produced from the JSON single');
  p('> source of truth (`data/forum.json` + `data/countries/*.json`) by');
  p('> `scripts/gen-catalog.js`, which `build.js` runs on every build. To refresh:');
  p('> `node scripts/gen-catalog.js`. See [`context.md`](context.md) for domain');
  p('> background and [`docs/adrs/`](docs/adrs/) for the architecture.');
  p('');
  p(`_Last generated: ${new Date().toISOString().slice(0, 10)} · ` +
    `${countries.length} countries · ${d.parties.length} listed parties · ` +
    `${d.armedMovements.movements.length} armed movements · ` +
    `${d.regionalBodies.items.length} regional bodies · ` +
    `${d.relatedOrganizations.length} related organizations · ` +
    `${d.references.length} references._`);

  // ---- Contents ------------------------------------------------------------
  h('## Contents');
  [
    'Countries & FSP presidents',
    'Member parties',
    'Member parties in government',
    'Membership rosters over time',
    'Armed & guerrilla movements',
    'Regional integration bodies',
    'Related organizations',
    'References',
  ].forEach((s) => p(`- [${s}](#${s.toLowerCase().replace(/[^a-z0-9 ]/g, '').replace(/ /g, '-')})`));

  // ---- Countries -----------------------------------------------------------
  h('## Countries & FSP presidents');
  p('Countries with a dossier here (presidential succession since 1990, with');
  p('Foro de São Paulo member/affiliated presidents flagged). **This is the set of');
  p('*tracked* countries — not an exhaustive list of Latin America.** Affiliations');
  p('marked *to verify* are not asserted as confirmed. See ADR-0009.');
  p('');
  p(`Total FSP-party presidential terms across tracked countries: **${totalFspTerms}**.`);
  p('');
  p('| Country | Code | FSP party | Status | FSP presidents (term) |');
  p('|---|---|---|---|---|');
  countries.forEach(({ meta, data }) => {
    const fspP = data.presidentialSuccession
      .filter((x) => x.fsp)
      .map((x) => `${x.name} (${yr(x.start)}–${yr(x.end)})`)
      .join('; ') || '—';
    p(`| [${cell(data.country)}](docs/countries/${meta.code}.html) | ${cell(meta.code)} | ` +
      `${cell(data.fspParty)} | ${cell(data.fspStatus)} | ${cell(fspP)} |`);
  });

  // Legislative control (lower house), where compiled (issue #106).
  const withLeg = countries.filter(({ data }) => Array.isArray(data.legislativeControl) && data.legislativeControl.length);
  if (withLeg.length) {
    p('');
    p('### Legislative control (lower house)');
    p('The FSP-member party’s standing in the lower chamber over time, where compiled');
    p('(issue #106). `majority`/`plurality`/`minority` describe the FSP party or its');
    p('governing coalition; `opposition` = out of government; `single-party` = one-party state.');
    withLeg.forEach(({ data }) => {
      const spans = data.legislativeControl
        .map((l) => `${yr(l.start)}–${yr(l.end)}: **${cell(l.fspBloc)}**`)
        .join(' · ');
      p(`- **${cell(data.country)}** (${cell(data.legislativeControl[0].fspParty || '')}): ${spans}`);
    });
  }

  // ---- Parties -------------------------------------------------------------
  h('## Member parties');
  p('A curated, non-exhaustive list of notable member parties (from');
  p('`forum.json → parties[]`). The full membership is in the rosters below.');
  p('');
  p('| Party | Abbr | Country | Founding member | Notes |');
  p('|---|---|---|---|---|');
  d.parties.forEach((x) => {
    const f = x.founding === true ? 'yes' : x.founding === false ? 'no' : '—';
    p(`| ${cell(x.name)} | ${cell(x.abbr || '')} | ${cell(x.country)} | ${f} | ${cell(x.notes || '')} |`);
  });

  // ---- Members in government ------------------------------------------------
  h('## Member parties in government');
  p(cell(d.membersInGovernment.note || ''));
  p('');
  p('| Country | Party | FSP status | Heads of state/government |');
  p('|---|---|---|---|');
  d.membersInGovernment.entries.forEach((e) => {
    const heads = Array.isArray(e.heads) ? e.heads.join('; ') : (e.heads || '');
    p(`| ${cell(e.country)} | ${cell(e.party)} | ${cell(e.fspStatus || '')} | ${cell(heads)} |`);
  });

  // ---- Membership rosters --------------------------------------------------
  h('## Membership rosters over time');
  p('Snapshots of the Forum’s membership at documented points, from Regalado');
  p('(2008). Counts are organizations / countries per snapshot.');
  p('');
  d.membershipRosters.forEach((r) => {
    const total = r.byCountry.reduce((n, c) => n + c.orgs.length, 0);
    p(`### ${cell(r.title)} — ${total} organizations, ${r.byCountry.length} countries`);
    if (r.note) { p(''); p(`_${cell(r.note)}_`); }
    p('');
    p('<details><summary>Full list by country</summary>');
    p('');
    r.byCountry.forEach((c) => p(`- **${cell(c.country)}** (${c.orgs.length}): ${cell(c.orgs.join(' · '))}`));
    p('');
    p('</details>');
    p('');
  });

  // ---- Armed movements -----------------------------------------------------
  h('## Armed & guerrilla movements');
  p(cell(d.armedMovements.note || ''));
  p('');
  p('| Movement | Abbr | Country | Period | Nature | Role in the Forum | Status |');
  p('|---|---|---|---|---|---|---|');
  d.armedMovements.movements.forEach((m) => {
    const role = (m.verified === false ? '(to verify) ' : '') + (m.fspRole || '');
    p(`| ${cell(m.name)} | ${cell(m.abbr || '')} | ${cell(m.country)} | ${cell(m.period || '')} | ` +
      `${cell(m.nature || '')} | ${cell(role)} | ${cell(m.currentStatus || '')} |`);
  });

  // ---- Regional bodies -----------------------------------------------------
  h('## Regional integration bodies');
  p(cell(d.regionalBodies.note || ''));
  p('');
  d.regionalBodies.items.forEach((b) => {
    p(`### ${cell(b.name)}${b.abbr ? ` (${cell(b.abbr)})` : ''}${b.founded ? ` — founded ${cell(b.founded)}` : ''}`);
    if (b.whatItIs) { p(''); p(cell(b.whatItIs)); }
    if (b.members) { p(''); p(`**Members:** ${cell(b.members)}`); }
    if (b.fspLink) { p(''); p(`**Link to the Forum:** ${cell(b.fspLink)}`); }
    p('');
  });

  // ---- Related organizations -----------------------------------------------
  h('## Related organizations');
  p('Distinct, coexisting networks often confused with the Forum (it has **not**');
  p('been renamed). See `context.md` for the Foro ≠ Grupo de Puebla distinction.');
  p('');
  d.relatedOrganizations.forEach((o) => {
    p(`### ${cell(o.name)}${o.founded ? ` — founded ${cell(o.founded)}` : ''}${o.place ? `, ${cell(o.place)}` : ''}`);
    if (o.composition) { p(''); p(`**Composition:** ${cell(o.composition)}`); }
    if (o.relationToForum) { p(''); p(cell(o.relationToForum)); }
    if (o.url) { p(''); p(`<${o.url}>`); }
    p('');
  });

  // ---- References ----------------------------------------------------------
  h('## References');
  p('Every cited source (`forum.json → references[]`). Each is also preserved in');
  p('the Internet Archive and as a local copy in the document vault (ADR-0004, ADR-0008).');
  p('');
  p('| id | Title | Type | URL |');
  p('|---|---|---|---|');
  d.references.forEach((r) => {
    p(`| \`${cell(r.id)}\` | ${cell(r.title)} | ${cell(r.type || '')} | ${r.url ? `<${r.url}>` : ''} |`);
  });

  return out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}

function write() {
  const md = generate();
  fs.writeFileSync(path.join(ROOT, 'CATALOG.md'), md);
  return md;
}

if (require.main === module) {
  write();
  console.log('Wrote CATALOG.md');
}

module.exports = { generate, write };
