#!/usr/bin/env node
'use strict';
/**
 * wayback-harvest.js — inventory the archived captures of the Foro de São Paulo
 * official site (forodesaopaulo.org) in the Internet Archive Wayback Machine.
 *
 * This is the first step of recovering historical content: it does NOT scrape
 * page bodies, it builds a reviewable index of WHAT exists in the archive so a
 * human (or a follow-up pass) can pull the high-value pages — meeting pages,
 * "declaração/declaración final", member lists, history pages.
 *
 * Output:
 *   data/wayback-inventory.json       full machine-readable inventory
 *   docs-research/wayback-inventory.md human-readable summary, useful pages first
 *
 * Usage:
 *   node scripts/wayback-harvest.js
 *   node scripts/wayback-harvest.js --domain=forodesaopaulo.org --limit=10000
 *
 * Network: requires outbound HTTPS to web.archive.org. Some sandboxed/CI
 * environments block archive.org by egress policy — run where the Internet
 * Archive is reachable (locally, or via the GitHub Action in
 * .github/workflows/wayback.yml). Behind a proxy on Node >= 22.21, run with
 * NODE_USE_ENV_PROXY=1.
 *
 * Exit codes: 0 = inventory written; 1 = the CDX query could not be reached.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT_JSON = path.join(ROOT, 'data', 'wayback-inventory.json');
const OUT_MD_DIR = path.join(ROOT, 'docs-research');
const OUT_MD = path.join(OUT_MD_DIR, 'wayback-inventory.md');
const CDX = 'https://web.archive.org/cdx/search/cdx';

// ---- CLI args -------------------------------------------------------------
const args = process.argv.slice(2);
const argVal = (name, fallback) => {
  const a = args.find((x) => x.startsWith(`--${name}=`));
  return a ? a.split('=').slice(1).join('=') : fallback;
};
const DOMAIN = argVal('domain', 'forodesaopaulo.org');
const LIMIT = parseInt(argVal('limit', '10000'), 10) || 10000;
const TIMEOUT_MS = (parseInt(argVal('timeout', '90'), 10) || 90) * 1000;

// Keywords that flag a capture as high-value for the chronology.
const USEFUL_PATTERNS = [
  /declarac/i, /declarat/i, /final/i,
  /encontro/i, /encuentro/i, /reunion/i, /reuni[aã]o/i,
  /historia/i, /hist[oó]ric/i, /quem-?somos/i, /quienes-?somos/i, /sobre/i,
  /membr/i, /miembr/i, /partido/i, /organiza/i, /integrant/i,
  /documento/i, /resoluc/i, /acta/i,
];

function isUseful(url) {
  return USEFUL_PATTERNS.some((re) => re.test(url));
}

function waybackUrl(timestamp, original) {
  return `https://web.archive.org/web/${timestamp}/${original}`;
}

function fmtTs(ts) {
  if (!ts || ts.length < 8) return ts || '';
  return `${ts.slice(0, 4)}-${ts.slice(4, 6)}-${ts.slice(6, 8)}`;
}

async function fetchCdx() {
  const params = new URLSearchParams({
    url: DOMAIN,
    matchType: 'domain',
    output: 'json',
    collapse: 'urlkey',
    fl: 'original,timestamp,statuscode,mimetype,digest',
    limit: String(LIMIT),
  });
  const ctrl = new AbortController();
  const t = setTimeout(() => ctrl.abort(), TIMEOUT_MS);
  try {
    const res = await fetch(`${CDX}?${params}`, {
      signal: ctrl.signal,
      headers: { 'User-Agent': 'fsp-wayback-harvest/1.0 (+https://github.com/cronologia/fsp)' },
    });
    if (!res.ok) throw new Error(`CDX returned HTTP ${res.status}`);
    return await res.json();
  } finally {
    clearTimeout(t);
  }
}

function buildInventory(rows) {
  // First row is the header (original,timestamp,statuscode,mimetype,digest).
  const [, ...data] = rows;
  // Group by original URL, tracking earliest/latest capture and capture count.
  const byUrl = new Map();
  for (const [original, timestamp, statuscode, mimetype] of data) {
    if (!byUrl.has(original)) {
      byUrl.set(original, {
        url: original,
        firstCapture: timestamp,
        lastCapture: timestamp,
        captures: 1,
        statuscode,
        mimetype,
        useful: isUseful(original),
      });
    } else {
      const e = byUrl.get(original);
      e.captures += 1;
      if (timestamp < e.firstCapture) e.firstCapture = timestamp;
      if (timestamp > e.lastCapture) e.lastCapture = timestamp;
    }
  }
  const entries = [...byUrl.values()].sort((a, b) => {
    if (a.useful !== b.useful) return a.useful ? -1 : 1; // useful first
    return a.url.localeCompare(b.url);
  });
  return entries;
}

function renderMarkdown(entries) {
  const useful = entries.filter((e) => e.useful);
  const lines = [];
  lines.push('# Wayback inventory — forodesaopaulo.org');
  lines.push('');
  lines.push('> Generated by `scripts/wayback-harvest.js`. This is an index of what');
  lines.push('> exists in the Internet Archive, not the harvested content itself.');
  lines.push('> Use the "high-value pages" list to recover meeting declarations,');
  lines.push('> member lists and history pages into `data/forum.json`.');
  lines.push('');
  lines.push(`- Domain: \`${DOMAIN}\``);
  lines.push(`- Generated: ${new Date().toISOString()}`);
  lines.push(`- Unique archived URLs: **${entries.length}** (high-value: **${useful.length}**)`);
  lines.push('');
  lines.push('## High-value pages');
  lines.push('');
  if (useful.length === 0) {
    lines.push('_None matched the high-value patterns — review the full inventory JSON._');
  } else {
    lines.push('| Page | Captures | First | Last | Latest snapshot |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const e of useful.slice(0, 200)) {
      lines.push(
        `| ${e.url} | ${e.captures} | ${fmtTs(e.firstCapture)} | ${fmtTs(e.lastCapture)} | [view](${waybackUrl(e.lastCapture, e.url)}) |`
      );
    }
  }
  lines.push('');
  lines.push(`_Full machine-readable inventory: \`data/wayback-inventory.json\` (${entries.length} URLs)._`);
  lines.push('');
  return lines.join('\n');
}

async function main() {
  console.log(`Querying Wayback CDX for ${DOMAIN} (limit ${LIMIT})…`);
  let rows;
  try {
    rows = await fetchCdx();
  } catch (err) {
    console.error(`Could not reach the Wayback CDX API: ${err.message}`);
    console.error('If you are in a sandbox that blocks archive.org, run this where the Internet Archive is reachable.');
    process.exit(1);
  }
  if (!Array.isArray(rows) || rows.length <= 1) {
    console.log('No captures found (empty CDX response).');
    fs.writeFileSync(OUT_JSON, JSON.stringify({ domain: DOMAIN, generated: new Date().toISOString(), entries: [] }, null, 2) + '\n');
    process.exit(0);
  }

  const entries = buildInventory(rows);
  const payload = {
    domain: DOMAIN,
    generated: new Date().toISOString(),
    uniqueUrls: entries.length,
    usefulUrls: entries.filter((e) => e.useful).length,
    entries,
  };

  fs.writeFileSync(OUT_JSON, JSON.stringify(payload, null, 2) + '\n');
  if (!fs.existsSync(OUT_MD_DIR)) fs.mkdirSync(OUT_MD_DIR, { recursive: true });
  fs.writeFileSync(OUT_MD, renderMarkdown(entries));

  console.log(
    `Wrote ${path.relative(ROOT, OUT_JSON)} and ${path.relative(ROOT, OUT_MD)} ` +
      `(${entries.length} URLs, ${payload.usefulUrls} high-value).`
  );
}

main().catch((err) => {
  console.error('wayback-harvest failed:', err);
  process.exit(1);
});
